Improve support for reverse proxy with nginx.
geminabox/geminabox pull request #367
Opened 2021-11-10 02:23 UTC by ChanthMiao

I need to deploy geminabox behind nginx under a subdirectory (e.g. /ruby), which is not supported.
So, I try to made it by modifying geminabox as this commit.

2022-06-28 01:30 UTC, tnir commented
@ChanthMiao Can you update changes as some files are conflicted?

2022-06-28 03:09 UTC, ChanthMiao commented
> @ChanthMiao Can you update changes as some files are conflicted?

I may update this PR next week.

2022-07-02 09:30 UTC, ChanthMiao commented
There are some checks failed. I need some time to fix it.

2022-07-02 12:56 UTC, ChanthMiao commented on lib/geminabox/server.rb
> +        Geminabox.base_path.gsub(/\/$/,'')
Already fixed.

2022-07-03 07:11 UTC, ChanthMiao commented
@tnir please review this PR again.

2022-07-03 10:23 UTC, ChanthMiao commented on lib/geminabox/server.rb
> +        Geminabox.base_path.sub(%r{/\/$/}, '')
> lib/geminabox/server.rb:33:37: C: [Correctable] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
        Geminabox.base_path.sub(%r{/\/$/}, '')
                                    ^^

@tnir Any suggestions? I am not a ruby regex professional.

2022-07-03 10:35 UTC, ChanthMiao commented on lib/geminabox/server.rb
> +        Geminabox.base_path.sub(%r{/\/$/}, '')
It should be fixed now.
```diff
diff --git a/lib/geminabox/server.rb b/lib/geminabox/server.rb
index 7eecc2a..4cc8a5b 100644
--- a/lib/geminabox/server.rb
+++ b/lib/geminabox/server.rb
@@ -30,7 +30,7 @@ module Geminabox
       end

       def base_path?
-        Geminabox.base_path.sub(%r{/\/$/}, '')
+        Geminabox.base_path.sub(%r{/$}, '')
       end

       def fixup_bundler_rubygems!
```

2022-07-03 10:37 UTC, ChanthMiao commented
@tnir, this time rubocop check should be ok!

2022-07-03 23:47 UTC, tnir requested changes
@ChanthMiao Would you mind adding tests for code you added? 🍀

2022-07-04 08:09 UTC, ChanthMiao commented
> @ChanthMiao Would you mind adding tests for code you added? 🍀

I can try it, but have no idea how to do it, currently.
This PR changes the urls in web pages. which only works (and make sense) behind a reserve proxy. I just do not know how to tests it in testscases.

2022-07-05 17:41 UTC, ChanthMiao commented
Maybe, we cant test it by running docker-compose in Github Actions. (e.g. <https://github.com/peter-evans/docker-compose-actions-workflow>)

@tnir any better suggestions?

2022-12-06 02:03 UTC, closed without merging